// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50001,
		Name:          "gateway.options.code",
		Tag:           "varint,50001,opt,name=code",
		Filename:      "proto/options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         50002,
		Name:          "gateway.options.resp_code",
		Tag:           "varint,50002,opt,name=resp_code",
		Filename:      "proto/options/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// 客户端 -> 网关 -> 服务 的入站 code（必填）
	//
	// optional uint32 code = 50001;
	E_Code = &file_proto_options_options_proto_extTypes[0]
	// 服务 -> 网关 -> 客户端 的回包 code（可选；不填则默认用同一个 code）
	//
	// optional uint32 resp_code = 50002;
	E_RespCode = &file_proto_options_options_proto_extTypes[1]
)

var File_proto_options_options_proto protoreflect.FileDescriptor

const file_proto_options_options_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/options/options.proto\x12\x0fgateway.options\x1a google/protobuf/descriptor.proto:4\n" +
	"\x04code\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\rR\x04code:=\n" +
	"\tresp_code\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\rR\brespCodeB\x0fZ\rproto/optionsb\x06proto3"

var file_proto_options_options_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_proto_options_options_proto_depIdxs = []int32{
	0, // 0: gateway.options.code:extendee -> google.protobuf.MethodOptions
	0, // 1: gateway.options.resp_code:extendee -> google.protobuf.MethodOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_options_options_proto_init() }
func file_proto_options_options_proto_init() {
	if File_proto_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_options_options_proto_rawDesc), len(file_proto_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_options_options_proto_goTypes,
		DependencyIndexes: file_proto_options_options_proto_depIdxs,
		ExtensionInfos:    file_proto_options_options_proto_extTypes,
	}.Build()
	File_proto_options_options_proto = out.File
	file_proto_options_options_proto_goTypes = nil
	file_proto_options_options_proto_depIdxs = nil
}
