// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/annotations/extra.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto_annotations_extra_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "annotations.white_list",
		Tag:           "varint,50001,opt,name=white_list",
		Filename:      "proto/annotations/extra.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool white_list = 50001;
	E_WhiteList = &file_proto_annotations_extra_proto_extTypes[0]
)

var File_proto_annotations_extra_proto protoreflect.FileDescriptor

const file_proto_annotations_extra_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/annotations/extra.proto\x12\vannotations\x1a google/protobuf/descriptor.proto:?\n" +
	"\n" +
	"white_list\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\twhiteListBKZIgithub.com/nathan77886/go-tools/protoc-gen-api-registry/proto/annotationsb\x06proto3"

var file_proto_annotations_extra_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_proto_annotations_extra_proto_depIdxs = []int32{
	0, // 0: annotations.white_list:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_annotations_extra_proto_init() }
func file_proto_annotations_extra_proto_init() {
	if File_proto_annotations_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_annotations_extra_proto_rawDesc), len(file_proto_annotations_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_annotations_extra_proto_goTypes,
		DependencyIndexes: file_proto_annotations_extra_proto_depIdxs,
		ExtensionInfos:    file_proto_annotations_extra_proto_extTypes,
	}.Build()
	File_proto_annotations_extra_proto = out.File
	file_proto_annotations_extra_proto_goTypes = nil
	file_proto_annotations_extra_proto_depIdxs = nil
}
