// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/annotations/extra.proto

package annotations

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增：前端权限分组（面包屑/菜单层级）
// 例：["用户管理","用户列表","封禁"]
type FrontGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontGroup) Reset() {
	*x = FrontGroup{}
	mi := &file_proto_annotations_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontGroup) ProtoMessage() {}

func (x *FrontGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_annotations_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontGroup.ProtoReflect.Descriptor instead.
func (*FrontGroup) Descriptor() ([]byte, []int) {
	return file_proto_annotations_extra_proto_rawDescGZIP(), []int{0}
}

func (x *FrontGroup) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var file_proto_annotations_extra_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "annotations.white_list",
		Tag:           "varint,50001,opt,name=white_list",
		Filename:      "proto/annotations/extra.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*FrontGroup)(nil),
		Field:         50002,
		Name:          "annotations.front_group",
		Tag:           "bytes,50002,opt,name=front_group",
		Filename:      "proto/annotations/extra.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool white_list = 50001;
	E_WhiteList = &file_proto_annotations_extra_proto_extTypes[0]
	// optional annotations.FrontGroup front_group = 50002;
	E_FrontGroup = &file_proto_annotations_extra_proto_extTypes[1]
)

var File_proto_annotations_extra_proto protoreflect.FileDescriptor

const file_proto_annotations_extra_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/annotations/extra.proto\x12\vannotations\x1a google/protobuf/descriptor.proto\"\"\n" +
	"\n" +
	"FrontGroup\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes:?\n" +
	"\n" +
	"white_list\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\bR\twhiteList:Z\n" +
	"\vfront_group\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\v2\x17.annotations.FrontGroupR\n" +
	"frontGroupBKZIgithub.com/nathan77886/go-tools/protoc-gen-api-registry/proto/annotationsb\x06proto3"

var (
	file_proto_annotations_extra_proto_rawDescOnce sync.Once
	file_proto_annotations_extra_proto_rawDescData []byte
)

func file_proto_annotations_extra_proto_rawDescGZIP() []byte {
	file_proto_annotations_extra_proto_rawDescOnce.Do(func() {
		file_proto_annotations_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_annotations_extra_proto_rawDesc), len(file_proto_annotations_extra_proto_rawDesc)))
	})
	return file_proto_annotations_extra_proto_rawDescData
}

var file_proto_annotations_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_annotations_extra_proto_goTypes = []any{
	(*FrontGroup)(nil),                 // 0: annotations.FrontGroup
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_proto_annotations_extra_proto_depIdxs = []int32{
	1, // 0: annotations.white_list:extendee -> google.protobuf.MethodOptions
	1, // 1: annotations.front_group:extendee -> google.protobuf.MethodOptions
	0, // 2: annotations.front_group:type_name -> annotations.FrontGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_annotations_extra_proto_init() }
func file_proto_annotations_extra_proto_init() {
	if File_proto_annotations_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_annotations_extra_proto_rawDesc), len(file_proto_annotations_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_annotations_extra_proto_goTypes,
		DependencyIndexes: file_proto_annotations_extra_proto_depIdxs,
		MessageInfos:      file_proto_annotations_extra_proto_msgTypes,
		ExtensionInfos:    file_proto_annotations_extra_proto_extTypes,
	}.Build()
	File_proto_annotations_extra_proto = out.File
	file_proto_annotations_extra_proto_goTypes = nil
	file_proto_annotations_extra_proto_depIdxs = nil
}
