// cmd/protoc-gen-gateway/main.go
package main

import (
	"path"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"

	optpb "github.com/nathan77886/go-tools/proto/options"
)

func main() {
	protogen.Options{}.Run(func(p *protogen.Plugin) error {
		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			generateFile(p, f)
		}
		return nil
	})
}

type methodMeta struct {
	Pkg          string
	SvcGoName    string
	MethodGoName string
	ReqIdent     protogen.GoIdent
	RespIdent    protogen.GoIdent
	Code         uint32
	RespCode     uint32
}

func generateFile(p *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_gateway.pb.go"
	g := p.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-gateway. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`  "context"`)
	g.P(`  "fmt"`)
	g.P(`  "sync"`)
	g.P(`  "google.golang.org/grpc"`)
	g.P(`  "google.golang.org/protobuf/proto"`)
	g.P(")")
	g.P()

	// 基础类型：线程安全路由 + Handler
	g.P(`type GatewayHandler func(ctx context.Context, payload []byte) (respCode uint32, out []byte, err error)`)
	g.P()
	g.P(`type Router struct {`)
	g.P(`  mu sync.RWMutex`)
	g.P(`  handlers map[uint32]GatewayHandler`)
	g.P(`}`)
	g.P()
	g.P(`func NewRouter() *Router { return &Router{handlers: make(map[uint32]GatewayHandler)} }`)
	g.P()
	g.P(`func (r *Router) Register(code uint32, h GatewayHandler) {`)
	g.P(`  r.mu.Lock(); defer r.mu.Unlock()`)
	g.P(`  if _, ok := r.handlers[code]; ok {`)
	g.P(`    panic(fmt.Sprintf("duplicate gateway code: %d", code))`)
	g.P(`  }`)
	g.P(`  r.handlers[code] = h`)
	g.P(`}`)
	g.P()
	g.P(`func (r *Router) Dispatch(ctx context.Context, code uint32, payload []byte) (uint32, []byte, error) {`)
	g.P(`  r.mu.RLock(); h, ok := r.handlers[code]; r.mu.RUnlock()`)
	g.P(`  if !ok { return 0, nil, fmt.Errorf("no handler for code %d", code) }`)
	g.P(`  return h(ctx, payload)`)
	g.P(`}`)
	g.P()

	// 收集带有扩展选项的方法
	var metas []methodMeta
	pkg := string(file.GoPackageName)

	for _, svc := range file.Services {
		for _, m := range svc.Methods {
			mo, _ := m.Desc.Options().(*descriptorpb.MethodOptions)
			if mo == nil {
				continue
			}
			var code, resp uint32

			if proto.HasExtension(mo, optpb.E_Code) {
				if v, ok := proto.GetExtension(mo, optpb.E_Code).(uint32); ok {
					code = v
				}
			}
			if proto.HasExtension(mo, optpb.E_RespCode) {
				if v, ok := proto.GetExtension(mo, optpb.E_RespCode).(uint32); ok {
					resp = v
				}
			}
			if code == 0 {
				// 未标注 code 的方法不参与网关路由
				continue
			}
			if resp == 0 {
				resp = code
			}

			metas = append(metas, methodMeta{
				Pkg:          pkg,
				SvcGoName:    svc.GoName,
				MethodGoName: m.GoName,
				ReqIdent:     m.Input.GoIdent,
				RespIdent:    m.Output.GoIdent,
				Code:         code,
				RespCode:     resp,
			})
		}
	}

	if len(metas) == 0 {
		return
	}

	// 为该 proto 文件内的 service 生成一个聚合 client set
	svcSet := map[string]struct{}{}
	for _, m := range metas {
		svcSet[m.SvcGoName] = struct{}{}
	}
	typeName := exportBase(path.Base(string(file.Desc.Path()))) + "GatewaySet"

	g.P(`// `, typeName, ` 聚合本 proto 文件中定义的 gRPC 客户端。`)
	g.P(`type `, typeName, ` struct {`)
	for s := range svcSet {
		g.P(`  `, lowerFirst(s), ` `, pkg, `.`, s, `Client`)
	}
	g.P(`}`)
	g.P()
	g.P(`// New`, typeName, ` 用一个 gRPC 连接构造所有客户端。`)
	g.P(`func New`, typeName, `(cc grpc.ClientConnInterface) *`, typeName, ` {`)
	g.P(`  return &`, typeName, `{`)
	for s := range svcSet {
		g.P(`    `, lowerFirst(s), `: `, pkg, `.New`, s, `Client(cc),`)
	}
	g.P(`  }`)
	g.P(`}`)
	g.P()

	// 注册函数：把所有 handler 注册进 Router
	regName := "Register" + exportBase(path.Base(string(file.Desc.Path()))) + "Gateway"
	g.P(`// `, regName, ` 将本文件内的所有网关处理器注册到路由器。`)
	g.P(`func `, regName, `(r *Router, set *`, typeName, `) {`)
	for _, m := range metas {
		h := handlerName(m)
		g.P(`  r.Register(`, m.Code, `, `, h, `(set))`)
	}
	g.P(`}`)
	g.P()

	// 具体 handler：反序列化 -> 调 RPC -> 序列化
	for _, m := range metas {
		h := handlerName(m)
		g.P(`func `, h, `(set *`, typeName, `) GatewayHandler {`)
		g.P(`  return func(ctx context.Context, payload []byte) (uint32, []byte, error) {`)
		g.P(`    in := new(`, m.ReqIdent.GoName, `)`)
		g.P(`    if err := proto.Unmarshal(payload, in); err != nil {`)
		g.P(`      return 0, nil, fmt.Errorf("unmarshal request failed: %w", err)`)
		g.P(`    }`)
		g.P(`    out, err := set.`, lowerFirst(m.SvcGoName), `.`, m.MethodGoName, `(ctx, in)`)
		g.P(`    if err != nil {`)
		g.P(`      return 0, nil, err`)
		g.P(`    }`)
		g.P(`    bs, err := proto.Marshal(out)`)
		g.P(`    if err != nil {`)
		g.P(`      return 0, nil, fmt.Errorf("marshal response failed: %w", err)`)
		g.P(`    }`)
		g.P(`    return `, m.RespCode, `, bs, nil`)
		g.P(`  }`)
		g.P(`}`)
		g.P()
	}
}

func handlerName(m methodMeta) string {
	return "handle_" + strings.ToLower(m.SvcGoName+"_"+m.MethodGoName+"_"+strconv.Itoa(int(m.Code)))
}

func exportBase(base string) string {
	if i := strings.LastIndexByte(base, '.'); i >= 0 {
		base = base[:i]
	}
	if base == "" {
		return "X"
	}
	return strings.ToUpper(base[:1]) + base[1:]
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
